database:
  host: localhost # host of your database
  port: 3306 # default port for MariaDB and MySQL
  database: db # name of your database. A database server can contain multiple databases
  user: username
  password: passy
server-id: "test"
core-chat: true
core-economy: false
#Keep Lowercase
censored-words:
    - fuck
    - shit
    - ass
    - bitch
    - hore
    - cunt
    - dick
    - pussy
    - crap
    - dammit
    - damn
    - damnit
banned-words: []